CREATE TABLE IF NOT EXISTS BOOK(
    IDENTIFIER NOT NULL PRIMARY KEY,
    TITLE,
    CREATOR,
    DOWNLOADS,
    PUBLISHER,
    VOLUME,
    ENCODING
);

CREATE TABLE IF NOT EXISTS BOOKMARK(
    IDENTIFIER NOT NULL PRIMARY KEY,
    LINE_NUMBER NOT NULL,
    TOTAL_LINES NOT NULL,
    SKIPPED NOT NULL,
    FINISHED NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTINUE_READING(
    CONTINUE_READING NOT NULL,
    LAST_UPDATE, 
    IDENTIFIER NOT NULL
); 
