-- SQLite
CREATE TABLE IF NOT EXISTS BOOK(
    IDENTIFIER NOT NULL PRIMARY KEY,
    TITLE,
    CREATOR,
    DOWNLOADS,
    PUBLISHER,
    VOLUME,
    ENCODING,
    DOWNLOADED
);
CREATE TABLE IF NOT EXISTS SUBJECT(
    IDENTIFIER NOT NULL,
    NAME NOT NULL,
    PRIMARY KEY(IDENTIFIER, NAME)
);
CREATE INDEX IF NOT EXISTS INDEX_NAME ON SUBJECT(NAME);
CREATE TABLE IF NOT EXISTS BOOKMARK(
    IDENTIFIER NOT NULL PRIMARY KEY,
    LINE_NUMBER NOT NULL,
    TOTAL_LINES NOT NULL,
    SKIPPED NOT NULL,
    FINISHED NOT NULL
);
CREATE TABLE IF NOT EXISTS CONTINUE_READING(
    CONTINUE_READING NOT NULL,
    LAST_UPDATE NOT NULL,
    IDENTIFIER NOT NULL PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS VOLUME(VOLUME NOT NULL PRIMARY KEY);
INSERT INTO VOLUME
select 0.5 --INSERT IF NOT EXISTS
WHERE NOT EXISTS(
        SELECT 1
        FROM VOLUME
    );
CREATE TABLE IF NOT EXISTS RATE(RATE NOT NULL PRIMARY KEY);
INSERT INTO RATE
select 200 --INSERT IF NOT EXISTS
WHERE NOT EXISTS(
        SELECT 1
        FROM RATE
    );