DROP TABLE BOOKMARK;
CREATE TABLE IF NOT EXISTS BOOKMARK(
    IDENTIFIER,
    LINE_NUMBER,
    TOTAL_LINES,
    SKIPPED,
    FINISHED
);
DELETE FROM BOOKMARK;
INSERT INTO BOOKMARK (IDENTIFIER, LINE_NUMBER, TOTAL_LINES, SKIPPED, FINISHED)
VALUES ('abrgdelhistoireg38256gut',117,9000,1,0),
('abrgdelhistoireg38257gut',9213,9213,0,0);

UPDATE CONTINUE_READING SET IDENTIFIER = 'abrgdelhistoireg38257gut', CONTINUE_READING = 1;
